version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install pytest

  build:
    commands:
      - echo "Running tests..."
      - |
        cat << EOF > test_sample.py
        def test_sample():
            assert True
        EOF
      - pytest --junitxml=test-results.xml test_sample.py

  post_build:
    commands: 
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          echo "Build succeeded"
        else
          echo "Build failed" 
          exit 1
        fi

reports:
  status:
    file-format: JUNITXML
    files:
      - test-results.xml
    discard-paths: no
  scikit-learn-test-status:
    file-format: JUNITXML
    files:
      - test-results.xml
    discard-paths: no

artifacts:
  files:
    - test-results.xml
  name: test-results