version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: github-oauth-token-KPUhtC:token

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install pytest

  pre_build:
    commands:
      - echo "GitHub Server Type: $GITHUB_SERVER_TYPE"
      - echo "Token length: ${#GITHUB_TOKEN}"
      - if [ -z "$GITHUB_TOKEN" ]; then echo "Token is empty"; else echo "Token is not empty"; fi
      - curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user

  build:
    commands:
      - echo "Running tests..."
      - |
        cat << EOF > test_sample.py
        def test_sample():
            assert True
        EOF
      - pytest --junitxml=test-results.xml test_sample.py

  post_build:
    commands: 
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          echo "Build succeeded"
        else
          echo "Build failed" 
          exit 1
        fi

reports:
  status:
    file-format: JUNITXML
    files:
      - test-results.xml
    discard-paths: no
  scikit-learn-test-status:
    file-format: JUNITXML
    files:
      - test-results.xml
    discard-paths: no

artifacts:
  files:
    - test-results.xml
  name: test-results